### ISSUE TITLE
Fix newline behavior of standard input/output channels

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#430] opened 2023-09-03 09:57 UTC
**Fix if test suites should explicitly set newlines for input/output channels.**

```yaml
- cases:
  - stdin: "echo\n"
    stdout: "echo\n"
    stderr: "echo\n" 
```

In the documentation, we'd better give some information on how the different (multiline) string options preserve/remove newlines.

**Fix how correct use of newlines in output channels is checked.** 

Are (trailing) newlines ignored? This currenly seems default behavior, but wouldn't it be better if this were some explicit setting?

**Comment by niknetniko** [comment] 2023-11-24 10:48
I did not see this issue, so duplicate of the newer issue #462.

**Closed by niknetniko** 2023-11-24 10:48 UTC
